### ISSUE TITLE
Problema com envio HTML

### ISSUE THREAD

**Issue by mariopacio** [saas-dev/smtp-api-examples#2]
Boa tarde, estamos com dois problemas nesta ferramenta:
1. Ao enviar HTML no body, o campo fica como null (resolvido usando utf8_encode())
2. Ao utilizar utf8_encode(), o e-mail chega com o html puro no cliente de e-mail

Aguardo retorno.

**Comment by fabioperrella** [comment]
adicinei um exemplo para envio com html no commit 7e5b1d3cde1132ec484724f634fd301687458548 veja se resolve por favor
